[workspace]

members = [
    "packages/core/crates/core-crypto",
    "packages/core/crates/core-hopr",
    "packages/core/crates/core-misc",
    "packages/core/crates/core-mixer",
    "packages/core/crates/core-network",
    "packages/core/crates/core-packet",
    "packages/core/crates/core-strategy",
    "packages/core/crates/core-types",
    "packages/core-ethereum/crates/core-ethereum-misc",
    "packages/core-ethereum/crates/core-ethereum-db",
    "packages/ethereum/crates/bindings",
    "packages/hopli",
    "packages/real/crates/real-base",
    "packages/hoprd/crates/hoprd-keypair",
    "packages/hoprd/crates/hoprd-misc",
    "packages/utils/crates/utils-db",
    "packages/utils/crates/utils-log",
    "packages/utils/crates/utils-metrics",
    "packages/utils/crates/utils-misc",
    "packages/utils/crates/utils-types"
]

[workspace.dependencies]
futures = "0.3.28"
futures-lite = "1.12.0"
libp2p = { git = "https://github.com/hoprnet/rust-libp2p.git", branch = "release/providence" }
serde = { version = "1.0" }
thiserror = "1.0"
wasm-pack = "0.12.0"
wasm-opt = "0.112.0"
wasm-bindgen = "0.2.86"

core-crypto = { path = "packages/core/crates/core-crypto", default-features = false }
core-network = { path = "packages/core/crates/core-network", default-features = false }
utils-log = { path = "packages/utils/crates/utils-log", default-features = false }
utils-misc = { path = "packages/utils/crates/utils-misc", default-features = false}
utils-metrics = { path = "packages/utils/crates/utils-metrics", default-features = false }


[profile.release]
opt-level = "s"     # optimize for small code size
#debug=true
