[package]
name = "real-base"
version = "0.1.0"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"
description = "Rust WASM modules for HOPR"
homepage = "https://hoprnet.org/"
repository = "https://github.com/hoprnet/hoprnet"
license = "GPL-3.0-only"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"] # rlib is necessary to run integration tests

[features]
default = [ "wasm", "console_error_panic_hook" ]
console_error_panic_hook = [ "dep:console_error_panic_hook" ]
wasm = [ "dep:wasm-bindgen", "dep:js-sys" ]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = { version = "0.3.63", optional = true }
thiserror = "1.0"
utils-log = { path = "../../../utils/crates/utils-log" }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.36"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
wasm-pack = { workspace = true }
wasm-opt = { workspace = true }

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O', '--enable-reference-types']
