[package]
name = "core-p2p"
version = "0.1.0"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = [
    "dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:js-sys", "dep:getrandom",
    "libp2p/wasm-bindgen", "dep:libp2p-wasm-ext",
    "core-network/wasm", "utils-log/wasm"
]

[dependencies]
libp2p = { workspace = true, features = ["noise", "request-response", "cbor", "macros"] }
libp2p-mplex = { git = "https://github.com/hoprnet/rust-libp2p.git", branch = "release/providence" }
futures = "0.3.28"
futures-lite = "1.12.0"
serde = { workspace = true, features = ["derive"]}
syn = "2.0.27"      # needed for `features=["macros"]` from `libp2p`
void = "1"

# wasm
libp2p-wasm-ext = { git = "https://github.com/hoprnet/rust-libp2p.git", branch = "release/providence", features = ["tcp"], optional = true }
getrandom = { version = "0.2.8", features = ["js"], optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = { version = "0.3.63", optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { version = "0.4.36", optional = true }
#wee_alloc = { version = "0.4.5", optional = true }

utils-log = { workspace = true }
core-network = { workspace = true }

[dev-dependencies]
more-asserts = "0.3.1"
env_logger = "0.10.0"
wasm-bindgen-test = "0.3.36"

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O', '--enable-reference-types']
